# Generated by Django 4.1.3 on 2022-11-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
